### ISSUE TITLE
concern about the batch normalization.

### ISSUE THREAD

**Issue by BentengMa** [pomonam/Self-Tuning-Networks#1]
Thanks for your great work.  I find that models do not contain the batch normalization (BN) layer in both MLP and CNNs, although bias=True is set in both convolution layers and linear layers.  Dose the learnable parameters in BN is special in response parameters in STN and delta-STN?

**Comment by pomonam** [comment]
Thank you for your interest. Yes, if you would like to use BN layers, you need to define your own similar to the linear layer so that it has response parameters.

**Comment by BentengMa** [comment]
Thank you for your reply.
